"use client"
import { useState } from "react"
import { Check, Mail, Send, Sparkles } from "lucide-react"
export default function ContactPage(){const [sent,setSent]=useState(false); return <div className="contact-page">
  <section className="page-hero"><div className="container"><span className="eyebrow"><Sparkles size={15}/> Say hello</span><h1>Let’s talk about<br/><em>good food.</em></h1><p>Have a recipe question, a story to share, or an idea for the blog? We’d genuinely love to hear from you.</p></div></section>
  <section className="container contact-layout"><aside><span className="kicker">Get in touch</span><h2>Our kitchen door is open.</h2><p>Send a note and we’ll get back to you as soon as we can. Recipe photos and enthusiastic details are always encouraged.</p><a href="mailto:hello@theorangeblog.com" className="contact-email"><span><Mail/></span><div><small>Email us</small><strong>hello@theorangeblog.com</strong></div></a><blockquote>“Cooking is love made visible.”<small>— Around our family table</small></blockquote></aside>
    <div className="contact-card">{sent?<div className="success-message"><span><Check/></span><h2>Your note is on its way.</h2><p>Thanks for reaching out. We’ll be in touch soon.</p><button onClick={()=>setSent(false)} className="text-link">Send another note</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true)}}><div className="form-row"><label>Your name<input required name="name" placeholder="Mara"/></label><label>Email address<input required name="email" type="email" placeholder="you@example.com"/></label></div><label>What’s this about?<input required name="subject" placeholder="A recipe question, idea, or hello"/></label><label>Your message<textarea required name="message" rows={7} placeholder="Tell us what’s cooking…"/></label><button className="submit-button" type="submit">Send message <Send size={17}/></button></form>}</div>
  </section>
  <section className="contact-note"><div className="container"><span>Recipe questions</span><span>Family stories</span><span>Kitchen wins</span><span>Collaborations</span></div></section>
  </div>}
