import Image from "next/image"
import Link from "next/link"
import { ArrowRight, Heart, NotebookPen, Sparkles } from "lucide-react"
export default function AboutPage(){return <div className="story-page">
  <section className="page-hero story-hero"><div className="container"><span className="eyebrow"><Sparkles size={15}/> Our story</span><h1>Recipes that feel<br/>like <em>home.</em></h1><p>The Orange began as a place to keep the dishes our family never wanted to lose—and grew into a table with room for everyone.</p></div></section>
  <section className="container story-grid"><div className="story-image"><Image src="https://j6vdsiddbdcswzdk.public.blob.vercel-storage.com/kitchen-appliances-in-professional-kitchen-in-a-mo-2023-11-27-05-13-33-utc-min-OTXf6odF52otNqbLcloZpo3ZZ7OsfG.jpg" alt="A warm working kitchen" fill className="card-photo"/></div><div className="story-copy"><span className="kicker">From our kitchen to yours</span><h2>A family recipe box, opened wide.</h2><p>What started as a personal collection of handwritten favorites has become a welcoming resource for home cooks. We believe the best recipes are clear, generous, and forgiving enough for real life.</p><p>Every dish here is chosen for the feeling it creates: a bright breakfast, a familiar weeknight dinner, or a dessert that brings everyone back to the table.</p><Link href="/gallery" className="text-link">Browse the recipe box <ArrowRight size={16}/></Link></div></section>
  <section className="values-section"><div className="container"><div className="section-heading"><div><span className="kicker">What guides us</span><h2>Simple values, joyful cooking</h2></div></div><div className="value-grid"><article><NotebookPen/><h3>Tested & trusted</h3><p>Clear instructions and dependable results, every time.</p></article><article><Heart/><h3>Made for sharing</h3><p>Food that helps people slow down and gather together.</p></article><article><Sparkles/><h3>Bright by nature</h3><p>Fresh flavors and small touches that make everyday meals shine.</p></article></div></div></section>
  <section className="story-cta container"><span className="kicker light">Pull up a chair</span><h2>There’s always room at our table.</h2><p>Questions, kitchen wins, and family recipes are all welcome.</p><Link href="/contact" className="button story-button">Say hello <ArrowRight size={17}/></Link></section>
  </div>}
